name: flutter_infinite_list
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_bloc: ^4.0.0
  bloc: ^4.0.0
  meta: ^1.1.6
  equatable: ^1.0.0
  http: ^0.12.0
  rxdart: ^0.23.1
  models: ^0.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true

  